name: tornpaper
description: A Flutter Container that looks like a (maybe torn) paper
version: 0.0.2
homepage: http://synchrondev.de

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  fast_noise: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
